A=23
print (A)

a=123
print (a)

In [ ]:
a=123
print (a)

In [ ]:
import sys
sys.executable


In [3]:
a=123
print (a)

123


In [ ]:
import sys
sys.executable


In [2]:
print("Hello from notebook ✅")


Hello from notebook ✅


In [1]:
import sys
print(sys.executable)


c:\Users\Lenovo\OneDrive\Backup_23102024\d_drive\PERSONAL\Career\Projects\DS_C247_Project\.venv\Scripts\python.exe


In [4]:
indian_cities = ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Lucknow']
print(indian_cities)

['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Lucknow']


In [5]:
# EXERCISE 1
cities = ["Delhi","mumbai","Delhi","Chennai","MUMBAI","Kolkata","chennai","Pune"]

# Create a set of unique city names in Title Case
unique_cities = {city.title() for city in cities}

# Print the set and its length
print("Unique cities (Title Case):")
print(unique_cities)
print(f"Length: {len(unique_cities)}")

Unique cities (Title Case):
{'Pune', 'Chennai', 'Mumbai', 'Kolkata', 'Delhi'}
Length: 5


In [10]:
cities = ["Delhi","mumbai","Delhi","Chennai","MUMBAI","Kolkata","chennai","Pune"]
s = set()
for i in cities:
    s.add(i.title())
print(s)
print (len(s))

{'Pune', 'Chennai', 'Mumbai', 'Kolkata', 'Delhi'}
5


In [11]:
cities = ["Delhi","mumbai","Delhi","Chennai","MUMBAI","Kolkata","chennai","Pune"]
s = set(cities)
print (s)

{'Pune', 'mumbai', 'MUMBAI', 'Chennai', 'chennai', 'Kolkata', 'Delhi'}


In [15]:
a = {"sql","python","excel","powerbi"}
b = {"python","tableau","statistics","excel"}

print (a & b)
print (a+(a&b))

{'excel', 'python'}


TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [18]:
# EXERCISE 2
a = {"sql","python","excel","powerbi"}
b = {"python","tableau","statistics","excel"}

# 1) Print common skills
print("Common skills:")
print(a & b)

# 2) Print all skills (unique)
print("\nAll skills (unique):")
print(a | b)

# 3) Print skills only in a (not in b)
print("\nSkills only in a:")
print(a - b)

Common skills:
{'excel', 'python'}

All skills (unique):
{'sql', 'powerbi', 'excel', 'statistics', 'python', 'tableau'}

Skills only in a:
{'sql', 'powerbi'}


In [ ]:
#### EXERCISE 3
#### Given:
nums = [5, 2, 5, 7, 2, 9, 9, 1]

new_list = [num for num ]

{1, 2, 5, 7, 9}
[1, 2, 5, 7, 9]


In [22]:
# EXERCISE 3
nums = [5, 2, 5, 7, 2, 9, 9, 1]

# Create a new list with duplicates removed while preserving first-seen order
result = list(dict.fromkeys(nums))
print (f"result: {result}")

print("Original list:")
print(nums)
print("\nList with duplicates removed (preserving order):")
print(result)

result: [5, 2, 7, 9, 1]
Original list:
[5, 2, 5, 7, 2, 9, 9, 1]

List with duplicates removed (preserving order):
[5, 2, 7, 9, 1]


In [23]:
nums = [5, 2, 5, 7, 2, 9, 9, 1]
new_list = []

for num in nums:
    if num not in new_list:
        new_list.append(num)
print (new_list)

[5, 2, 7, 9, 1]


In [ ]:
text = "data analytics needs data discipline"
text_list = text.split()
print (text_list)

#word_dict = {}

# for word in text_list:
#     print (word)
#     word_dict[word] = text_list.count(word)

# print (word_dict)

# word_dict = {x:text_list.count(x) for x in text_list}
# print (word_dict)


#for word in text_list:
#    if word in word_dict:
#        word_dict[word] += 1
#    else:
#        word_dict[word] = 1

['data', 'analytics', 'needs', 'data', 'discipline']
{'data': 2, 'analytics': 1, 'needs': 1, 'discipline': 1}


In [34]:
#### EXERCISE 5
#### Given student marks:
marks = {"Asha": {"SQL": 78, "Python": 85}, "Ravi": {"SQL": 66, "Python": 72}}
# 1) Add a new subject "Excel" for each student with marks: Asha=90, Ravi=80
for k,v in marks.items():
    #print (k,v)
    if k=="Asha":
        v["Excel"] = 90
    if k=="Ravi":
        v["Excel"] = 80
        

for k,v in marks.items():
    print (k,v)

Asha {'SQL': 78, 'Python': 85, 'Excel': 90}
Ravi {'SQL': 66, 'Python': 72, 'Excel': 80}


In [37]:
import numpy as np
vals = ["10", "20", "30", "40"]
vals_array = np.array(vals,dtype=int)
print (vals_array)
print (vals_array.dtype)

[10 20 30 40]
int64


In [ ]:
data = [[1,2,3],[4,5,6],[7,8,9]]
np_data = np.array(data)
print (np_data.shape,np_data.ndim,np_data.dtype)



(3, 3) 2 int64


array([7, 8, 9])

In [ ]:
a=[[ 1, 2 ,3, 4],[ 5 ,6 ,7 ,8],[ 9,10,11,12]]

np_a = np.array(a)
print (np_a)
col2 = np_a[1,:]
print (col2)

last_col = np_a[:,3]
print (last_col)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[ 4  8 12]


In [59]:
# EXERCISE 8
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

# Convert to numpy array
a_array = np.array(a)
print("Array:")
print(a_array)

# 1) Print the 2nd row
print("\n1) 2nd Row:")
print(a_array[1, :])

# 2) Print the last column
print("\n2) Last Column:")
print(a_array[:, -1])

# 3) Print sub-matrix of first 2 rows and last 2 columns
print("\n3) Sub-matrix (first 2 rows, last 2 columns):")
print(a_array[0:2, 2:4])

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1) 2nd Row:
[5 6 7 8]

2) Last Column:
[ 4  8 12]

3) Sub-matrix (first 2 rows, last 2 columns):
[[3 4]
 [7 8]]


In [67]:
#### EXERCISE 9
#### Given:
x = np.array([2, 4, 6, 8])
y = np.array([1, 2, 3, 4])

sum = x+y
diff = x-y
mul = x*y
div = x/y
div = np.round (div.astype(float),3)

print (f"sum: {sum}")
print (f"diff: {diff}")
print (f"mul: {mul}")
print (f"div: {div}")



sum: [ 3  6  9 12]
diff: [1 2 3 4]
mul: [ 2  8 18 32]
div: [2. 2. 2. 2.]


In [68]:
arr = np.array([10, 20, 30])
result = np.round(arr.astype(float), 2)
# To display with 2 decimals:
print([f"{x:.2f}" for x in result])
# Output: ['10.00', '20.00', '30.00']

['10.00', '20.00', '30.00']


In [70]:
#### EXERCISE 10
#### Given:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print (A*B)
print (A@B)

print (np.matmul(A,B))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [77]:
#### EXERCISE 11
#### Given:
a = np.array([12, 7, 3, 7, 9, 12, 7])

print (np.mean(a))
print (np.median(a))

print("Mean =", np.mean(a))
print("Median =", np.median(a))

print (f"Mean = {np.mean(a)}")
print (f"Median = {np.median(a)}")


8.142857142857142
7.0
Mean = 8.142857142857142
Median = 7.0
Mean = 8.142857142857142
Median = 7.0


In [72]:
# EXERCISE 11
a = np.array([12, 7, 3, 7, 9, 12, 7])

# 1) Compute mean
mean = np.mean(a)
print(f"1) Mean: {mean}")

# 2) Compute median
median = np.median(a)
print(f"2) Median: {median}")

1) Mean: 8.142857142857142
2) Median: 7.0


In [81]:
# EXERCISE 12
a = np.array([[5, 7, 9],
              [2, 4, 6],
              [8, 1, 3]])

print("Array:")
print(a)

# 1) Print row-wise sum
print("\n1) Row-wise sum:")
row_sum = np.sum(a, axis=1)
print(row_sum)

# 2) Print column-wise mean
print("\n2) Column-wise mean:")
col_mean = np.mean(a, axis=0)
print(col_mean)
max = np.max(a,axis=1)
min = np.min(a,axis=0)

print(f"Max: {max}, Min: {min}")

Array:
[[5 7 9]
 [2 4 6]
 [8 1 3]]

1) Row-wise sum:
[21 12 12]

2) Column-wise mean:
[5. 4. 6.]
Max: [9 6 8], Min: [2 1 3]


In [82]:
# EXERCISE 14: Fenced Matrix (All boundary elements 1, rest all zero)
rows, cols = 3, 4

# Create a matrix filled with zeros
matrix = np.zeros((rows, cols), dtype=int)

# Set all boundary elements to 1
matrix[0, :] = 1      # First row
matrix[-1, :] = 1     # Last row
matrix[:, 0] = 1      # First column
matrix[:, -1] = 1     # Last column

print(f"Fenced Matrix ({rows}x{cols}):")
print(matrix)

Fenced Matrix (3x4):
[[1 1 1 1]
 [1 0 0 1]
 [1 1 1 1]]


In [83]:
# EXERCISE 14: Alternative Approaches

# Approach 2: Using np.pad()
print("Approach 2: Using np.pad()")
rows, cols = 3, 4
inner_matrix = np.zeros((rows-2, cols-2), dtype=int)
matrix2 = np.pad(inner_matrix, 1, constant_values=1)
print(matrix2)

# Approach 3: Using np.ones() and setting interior to 0
print("\nApproach 3: Using np.ones() and setting interior to 0")
matrix3 = np.ones((rows, cols), dtype=int)
matrix3[1:-1, 1:-1] = 0
print(matrix3)

# Approach 4: Using list comprehension
print("\nApproach 4: Using list comprehension")
matrix4 = np.array([[1 if i == 0 or i == rows-1 or j == 0 or j == cols-1 else 0 
                     for j in range(cols)] for i in range(rows)])
print(matrix4)

Approach 2: Using np.pad()
[[1 1 1 1]
 [1 0 0 1]
 [1 1 1 1]]

Approach 3: Using np.ones() and setting interior to 0
[[1 1 1 1]
 [1 0 0 1]
 [1 1 1 1]]

Approach 4: Using list comprehension
[[1 1 1 1]
 [1 0 0 1]
 [1 1 1 1]]


In [86]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [92]:
x = np.ones((4,4),dtype=int)
print (x)

x[1:-1,1:-1] = 0
print (x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]
