In [4]:
import numpy as np


In [6]:
arr = np.arange(1,15)
print (arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
reshaped_arr = arr.reshape(2,7)
print (reshaped_arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
print (reshaped_arr.size)
print (reshaped_arr.shape)
print (reshaped_arr.ndim)

14
(2, 7)
2
