In [4]:
import numpy as np


In [6]:
arr = np.arange(1,15)
print (arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
reshaped_arr = arr.reshape(2,7)
print (reshaped_arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
print (reshaped_arr.size)
print (reshaped_arr.shape)
print (reshaped_arr.ndim)

14
(2, 7)
2


In [18]:
temp = np.array([1,2,3,43,5,345,34,5,12])
temp_mean = np.mean(temp)
temp_max = np.max(temp)
temp_min = np.min(temp)
temp_std = np.std(temp)
print (temp_mean)
print (temp_max)
print (temp_min)
print (temp_std)


50.0
345
1
105.27107864936124


In [20]:
temp_per = np.percentile(temp,50)


In [21]:
print (temp)
print (temp_per)

[  1   2   3  43   5 345  34   5  12]
5.0


In [23]:
temp_size = np.size(temp)
print (temp_size)

9


In [25]:
temp_prod = np.prod(temp)
print (temp_prod)

907902000


In [26]:
reshape_temp = temp.reshape(3,3)
print (reshape_temp)

[[  1   2   3]
 [ 43   5 345]
 [ 34   5  12]]


In [30]:
temp_cumsum = np.cumsum(temp)
print (temp)
print (temp_cumsum)

[  1   2   3  43   5 345  34   5  12]
[  1   3   6  49  54 399 433 438 450]


In [29]:
temp_cumprod = np.cumprod (temp)
print (temp_cumprod)

[        1         2         6       258      1290    445050  15131700
  75658500 907902000]


In [34]:
import pandas as pd
series1 = pd.Series([1,2,3,4,5])
series2 = pd.Series([1,2,3,4,5,6,7],index=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])
print (series1,series2)

0    1
1    2
2    3
3    4
4    5
dtype: int64 Mon    1
Tue    2
Wed    3
Thu    4
Fri    5
Sat    6
Sun    7
dtype: int64


In [36]:
#convert the dictionary to series 
s =  pd.Series ({"Mon":23,"Tue":34,"Wed":45,"Thu":56,"Fri":67})
print (s)

Mon    23
Tue    34
Wed    45
Thu    56
Fri    67
dtype: int64


In [37]:
s[(s>30) & (s<60)]

Tue    34
Wed    45
Thu    56
dtype: int64

In [39]:
s.shape

(5,)

In [40]:
s.dtype

dtype('int64')

In [41]:
#series is a single column, and multiple cols is a dataframe 

In [42]:
s.index

Index(['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], dtype='str')

In [43]:
s.size

5

In [ ]:
temp_Series = pd.Series(temp)
temp_Series_ind = pd.Series (temp_Series, index)
print (temp_Series)


0      1
1      2
2      3
3     43
4      5
5    345
6     34
7      5
8     12
dtype: int64


In [60]:
Region_A = pd.Series ([100,200,132,40,5], index=["Jan","Feb","Mar","Apr","May"])
Region_B = pd.Series ([60,7,88,99,150], index=["Jan","Feb","Mar","Apr","May"])

total = Region_A+Region_B
print (total)

Jan    160
Feb    207
Mar    220
Apr    139
May    155
dtype: int64


In [54]:
type(np.nan)

float

In [55]:
Region_A.prod()

np.int64(120)

In [56]:
Region_A[0:10].prod()

np.int64(120)

In [58]:
x=np.array([2**63-1], dtype=np.int64)
y=(x*2).astype(np.int64)
print (y)

[-2]


In [62]:
def sales_category(sales):
    if sales < 100:
        return "Low"
    elif sales < 5000:
        return "Medium"
    else:
        return "High"
    
tagged_region_A = Region_A.apply(sales_category)
print (tagged_region_A)

Jan    Medium
Feb    Medium
Mar    Medium
Apr       Low
May       Low
dtype: str
