In [12]:
import pandas as pd

In [13]:
print ("hello")

hello


In [14]:
df = pd.read_csv("sheets/day.csv")

In [15]:
df["season"].count()

np.int64(730)

In [16]:
df["season"].unique()

array([1, 2, 3, 4])

In [17]:
df["season"].nunique()

4

In [18]:
df["season"].value_counts()

season
3    188
2    184
1    180
4    178
Name: count, dtype: int64

In [19]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600


In [20]:
df.nunique()

instant       730
dteday        730
season          4
yr              2
mnth           12
holiday         2
weekday         7
workingday      2
weathersit      3
temp          498
atemp         689
hum           594
windspeed     649
casual        605
registered    678
cnt           695
dtype: int64

In [21]:
df.count()

instant       730
dteday        730
season        730
yr            730
mnth          730
holiday       730
weekday       730
workingday    730
weathersit    730
temp          730
atemp         730
hum           730
windspeed     730
casual        730
registered    730
cnt           730
dtype: int64

In [22]:
df["season"].unique()

array([1, 2, 3, 4])

In [23]:
df.nunique()

instant       730
dteday        730
season          4
yr              2
mnth           12
holiday         2
weekday         7
workingday      2
weathersit      3
temp          498
atemp         689
hum           594
windspeed     649
casual        605
registered    678
cnt           695
dtype: int64

In [24]:
df[df["season"]==2]["season"].count()

np.int64(184)

In [25]:
sub_df=df[["season","temp","hum"]].sample(10)

In [26]:
sub_df.sort_values("temp")

,season,temp,hum
39,1,5.526103,49.4783
25,1,8.917500,86.2500
360,1,13.325000,76.2500
671,4,14.076653,49.1250
107,2,21.012500,54.2500
458,2,22.208347,46.9583
263,3,24.395000,90.0000
166,2,25.761653,68.8333
541,3,25.864153,37.3333
574,3,29.588347,62.3750


In [36]:
df[df["season"]==2].head(5)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
79,80,21-03-2018,2,0,3,0,3,1,2,17.647835,20.48675,73.7391,19.348461,401,1676,2077
80,81,22-03-2018,2,0,3,0,4,1,1,18.108347,22.03210,62.4583,15.125250,460,2243,2703
81,82,23-03-2018,2,0,3,0,5,1,2,14.225237,16.89695,83.9565,15.695487,203,1918,2121
82,83,24-03-2018,2,0,3,0,6,0,2,11.685000,13.54165,80.5833,16.333729,166,1699,1865
83,84,25-03-2018,2,0,3,0,0,0,1,10.830847,12.81560,49.5000,15.458575,300,1910,2210


In [38]:
sub_df.sort_values("temp",ascending=False)

,season,temp,hum
574,3,29.588347,62.3750
541,3,25.864153,37.3333
166,2,25.761653,68.8333
263,3,24.395000,90.0000
458,2,22.208347,46.9583
107,2,21.012500,54.2500
671,4,14.076653,49.1250
360,1,13.325000,76.2500
25,1,8.917500,86.2500
39,1,5.526103,49.4783


In [39]:
sub_df.sort_values(["season","temp"],ascending=[True,False])

,season,temp,hum
360,1,13.325000,76.2500
25,1,8.917500,86.2500
39,1,5.526103,49.4783
166,2,25.761653,68.8333
458,2,22.208347,46.9583
107,2,21.012500,54.2500
574,3,29.588347,62.3750
541,3,25.864153,37.3333
263,3,24.395000,90.0000
671,4,14.076653,49.1250


In [40]:
sub_df.sort_values(["season","temp"],ascending=[True,False])

,season,temp,hum
360,1,13.325000,76.2500
25,1,8.917500,86.2500
39,1,5.526103,49.4783
166,2,25.761653,68.8333
458,2,22.208347,46.9583
107,2,21.012500,54.2500
574,3,29.588347,62.3750
541,3,25.864153,37.3333
263,3,24.395000,90.0000
671,4,14.076653,49.1250


In [41]:
for index,i in sub_df.iterrows():
    print (index,i["season"], i["temp"],i["hum"])

263 3.0 24.395 90.0
107 2.0 21.0125 54.25
458 2.0 22.208347 46.9583
39 1.0 5.526103 49.4783
360 1.0 13.325 76.25
541 3.0 25.864153 37.3333
671 4.0 14.076653 49.125
574 3.0 29.588347 62.375
25 1.0 8.9175 86.25
166 2.0 25.761653 68.8333


In [43]:
df.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='str')

In [46]:
for index,i in df.iterrows():
    print (f"index: {index}: values: {i["weathersit"],i["temp"],i["hum"]}")

index: 0: values: (2, 14.110847, 80.5833)
index: 1: values: (2, 14.902598, 69.6087)
index: 2: values: (1, 8.050924, 43.7273)
index: 3: values: (1, 8.2, 59.0435)
index: 4: values: (1, 9.305237, 43.6957)
index: 5: values: (1, 8.378268, 51.8261)
index: 6: values: (2, 8.057402, 49.8696)
index: 7: values: (2, 6.765, 53.5833)
index: 8: values: (1, 5.671653, 43.4167)
index: 9: values: (1, 6.184153, 48.2917)
index: 10: values: (2, 6.932731, 68.6364)
index: 11: values: (1, 7.081807, 59.9545)
index: 12: values: (1, 6.765, 47.0417)
index: 13: values: (1, 6.59567, 53.7826)
index: 14: values: (2, 9.566653, 49.875)
index: 15: values: (1, 9.498347, 48.375)
index: 16: values: (2, 7.209153, 53.75)
index: 17: values: (2, 8.883347, 86.1667)
index: 18: values: (2, 11.979134, 74.1739)
index: 19: values: (2, 10.728347, 53.8333)
index: 20: values: (1, 7.2775, 45.7083)
index: 21: values: (1, 2.4243464, 40.0)
index: 22: values: (1, 3.9573897, 43.6522)
index: 23: values: (1, 3.9930433, 49.1739)
index: 24: value

In [48]:
df["weekday"].unique()

array([1, 2, 3, 4, 5, 6, 0])

In [52]:
def week_map(value):
    d={1:"Monday",2:"Tuesday",3:"Wednesday",4:"Thursday",5:"Friday",6:"Saturday",0:"Sunday"}
    return d[value]

In [53]:
df["weekday_mod"]=df["weekday"].apply(week_map)

In [54]:
df["weekday_mod"]

0         Monday
1        Tuesday
2      Wednesday
3       Thursday
4         Friday
         ...    
725       Friday
726     Saturday
727       Sunday
728       Monday
729      Tuesday
Name: weekday_mod, Length: 730, dtype: str

In [55]:
df["weekday_mod"].str.upper()

0         MONDAY
1        TUESDAY
2      WEDNESDAY
3       THURSDAY
4         FRIDAY
         ...    
725       FRIDAY
726     SATURDAY
727       SUNDAY
728       MONDAY
729      TUESDAY
Name: weekday_mod, Length: 730, dtype: str

In [56]:
df["weekday_mod"].str.lower()

0         monday
1        tuesday
2      wednesday
3       thursday
4         friday
         ...    
725       friday
726     saturday
727       sunday
728       monday
729      tuesday
Name: weekday_mod, Length: 730, dtype: str

In [57]:
df["weekday_mod"].str.title()

0         Monday
1        Tuesday
2      Wednesday
3       Thursday
4         Friday
         ...    
725       Friday
726     Saturday
727       Sunday
728       Monday
729      Tuesday
Name: weekday_mod, Length: 730, dtype: str

In [58]:
df["weekday_mod"].str.len()

0      6
1      7
2      9
3      8
4      6
      ..
725    6
726    8
727    6
728    6
729    7
Name: weekday_mod, Length: 730, dtype: int64

In [59]:
df["weekday_mod"].str.replace("M","Q")

0         Qonday
1        Tuesday
2      Wednesday
3       Thursday
4         Friday
         ...    
725       Friday
726     Saturday
727       Sunday
728       Qonday
729      Tuesday
Name: weekday_mod, Length: 730, dtype: str

In [64]:
pd.get_option("display.max_rows")

60

In [68]:
pd.set_option("display.max_columns",5)

In [69]:
df.head()

,instant,dteday,...,cnt,weekday_mod
0,1,01-01-2018,...,985,Monday
1,2,02-01-2018,...,801,Tuesday
2,3,03-01-2018,...,1349,Wednesday
3,4,04-01-2018,...,1562,Thursday
4,5,05-01-2018,...,1600,Friday


In [73]:
pd.set_option("display.max_rows",10)

In [75]:
pd.reset_option("all")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_46816\3365680546.py:1: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.reset_option("all")
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_46816\3365680546.py:1: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.reset_option("all")


In [ ]:
pd.set_option("display")

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,weekday_mod
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985,Monday
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801,Tuesday
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349,Wednesday
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562,Thursday
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600,Friday


In [80]:
pd.set_option("display.max_columns", 5)

In [ ]:
df.head()

,instant,dteday,...,cnt,weekday_mod
4,5,05-01-2018,...,1600,Friday


In [81]:
pd.reset_option("all")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_46816\3365680546.py:1: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.reset_option("all")
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_46816\3365680546.py:1: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.reset_option("all")


In [82]:
df.isnull().sum()

instant        0
dteday         0
season         0
yr             0
mnth           0
holiday        0
weekday        0
workingday     0
weathersit     0
temp           0
atemp          0
hum            0
windspeed      0
casual         0
registered     0
cnt            0
weekday_mod    0
dtype: int64

In [83]:
df.isnull().sum()

instant        0
dteday         0
season         0
yr             0
mnth           0
holiday        0
weekday        0
workingday     0
weathersit     0
temp           0
atemp          0
hum            0
windspeed      0
casual         0
registered     0
cnt            0
weekday_mod    0
dtype: int64

In [84]:
100*df.isna().mean()

instant        0.0
dteday         0.0
season         0.0
yr             0.0
mnth           0.0
holiday        0.0
weekday        0.0
workingday     0.0
weathersit     0.0
temp           0.0
atemp          0.0
hum            0.0
windspeed      0.0
casual         0.0
registered     0.0
cnt            0.0
weekday_mod    0.0
dtype: float64

In [88]:
import numpy as np
import pandas as pd
data = {
    'Patient_ID': ['P001', 'P002', 'P003', 'P004', 'P005'],
    'Heart_Rate (bpm)': [78, np.nan, 85, 72, 90],
    'Blood_Pressure (mmHg)': ['120/80', '118/76', np.nan, '110/70', '130/85'],
    'Temperature (°C)': [36.8, 37.2, 38.0, np.nan, 37.5],
    'Oxygen_Saturation (%)': [98, 96, 94, 97, np.nan]
}

df = pd.DataFrame(data)
df.isnull().sum()
100*df.isna().mean()

Patient_ID                0.0
Heart_Rate (bpm)         20.0
Blood_Pressure (mmHg)    20.0
Temperature (°C)         20.0
Oxygen_Saturation (%)    20.0
dtype: float64

In [93]:
#ignore the columns which have more than 50% missing values
#otherwise we impute
#median is preferred when compared with mean because mean is affected by outliers but median is not affected by outliers

heart_rate_mean = df['Heart_Rate (bpm)'].mean()
print(heart_rate_mean)


81.25


In [94]:
df['Heart_Rate (bpm)'] = df['Heart_Rate (bpm)'].fillna(heart_rate_mean)

In [95]:
df['Heart_Rate (bpm)']

0    78.00
1    81.25
2    85.00
3    72.00
4    90.00
Name: Heart_Rate (bpm), dtype: float64

In [96]:
temp_median = df['Temperature (°C)'].median()
print(temp_median)
df['Temperature (°C)'] = df['Temperature (°C)'].fillna(temp_median)

37.35


In [97]:
df['Temperature (°C)']

0    36.80
1    37.20
2    38.00
3    37.35
4    37.50
Name: Temperature (°C), dtype: float64

In [98]:
df.drop_duplicates()

,Patient_ID,Heart_Rate (bpm),Blood_Pressure (mmHg),Temperature (°C),Oxygen_Saturation (%)
0,P001,78.00,120/80,36.80,98.0
1,P002,81.25,118/76,37.20,96.0
2,P003,85.00,NaN,38.00,94.0
3,P004,72.00,110/70,37.35,97.0
4,P005,90.00,130/85,37.50,NaN


In [99]:
df.drop_duplicates(subset=["Patient_ID"])

,Patient_ID,Heart_Rate (bpm),Blood_Pressure (mmHg),Temperature (°C),Oxygen_Saturation (%)
0,P001,78.00,120/80,36.80,98.0
1,P002,81.25,118/76,37.20,96.0
2,P003,85.00,NaN,38.00,94.0
3,P004,72.00,110/70,37.35,97.0
4,P005,90.00,130/85,37.50,NaN


In [100]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool